// src/tools/productivity/infinite-type/InfiniteType.tsx
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Motion } from '@/core/motion/motion';
import { Stagger } from '@/core/motion/core/Stagger';
import { zoomIn } from '@/core/motion/presets/zoomIn';
import { MdWarningAmber } from 'react-icons/md';
import { FiCopy } from 'react-icons/fi';
import { useToast } from '@/core/hooks/useToast';
import { useInfiniteType } from './useInfiniteType';
import { Controls } from './Controls';
import { Viewport } from './Viewport';

const RESIZE_THRESHOLD = 20;
const TOOLKIT_URL = 'https://toolpabitrams.pages.dev/';

function formatTime(ms: number): string {
  const totalSec = Math.floor(ms / 1000);
  const h = Math.floor(totalSec / 3600);
  const m = Math.floor((totalSec % 3600) / 60);
  const s = totalSec % 60;
  if (h > 0) {
    return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  }
  return `${m}:${s.toString().padStart(2, '0')}`;
}

export const InfiniteType: React.FC = () => {
  const {
    state,
    pool,
    setPool,
    start,
    stop,
    isRunning,
    typeChar,
    backspace,
    enter,
  } = useInfiniteType();

  const { showToast } = useToast();
  const inputRef = useRef<HTMLInputElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const probeRef = useRef<HTMLSpanElement>(null);
  const [containerWidth, setContainerWidth] = useState(0);
  const [charWidth, setCharWidth] = useState(0);
  const [isFocused, setIsFocused] = useState(false);
  const [, setTick] = useState(0);
  const startWidth = useRef(0);
  const resizeWarned = useRef(false);

  const activeLineIndex = state.lines.length - 1;
  const activeLine = state.lines[activeLineIndex];
  const activeTypedLen = activeLine ? activeLine.typed.length : 0;

  const maxChars = useMemo(() => {
    if (containerWidth <= 0 || charWidth <= 0) return 40;
    return Math.max(1, Math.floor(containerWidth / charWidth));
  }, [containerWidth, charWidth]);

  useEffect(() => {
    if (isRunning) {
      inputRef.current?.focus({ preventScroll: true });
    }
  }, [isRunning]);

  useEffect(() => {
    if (!isRunning) return;
    const id = setInterval(() => setTick((t) => t + 1), 1000);
    return () => clearInterval(id);
  }, [isRunning]);

  useEffect(() => {
    if (!isRunning) return;
    if (startWidth.current === 0) return;
    if (Math.abs(containerWidth - startWidth.current) > RESIZE_THRESHOLD) {
      stop();
      if (!resizeWarned.current) {
        resizeWarned.current = true;
        showToast(
          'warning',
          <MdWarningAmber size={20} />,
          'Screen size changed',
          'Session stopped. Press Start to continue with the new layout.'
        );
      }
    }
  }, [containerWidth, isRunning, stop, showToast]);

  useEffect(() => {
    if (!isRunning) return;
    const inputEl = inputRef.current;
    const containerEl = containerRef.current;
    if (!inputEl || !containerEl) return;
    const activeEl = containerEl.lastElementChild as HTMLElement | null;
    if (!activeEl) return;

    const raf = requestAnimationFrame(() => {
      const rect = activeEl.getBoundingClientRect();
      inputEl.style.transform = `translate(${rect.left}px, ${Math.max(0, rect.top)}px)`;
    });
    return () => cancelAnimationFrame(raf);
  }, [activeLineIndex, activeTypedLen, isRunning]);

  const handleStart = () => {
    let cw = containerWidth;
    let pw = charWidth;

    if (containerRef.current) {
      const w = containerRef.current.getBoundingClientRect().width;
      if (w > 0) cw = w;
    }
    if (probeRef.current) {
      const w = probeRef.current.getBoundingClientRect().width;
      if (w > 0) pw = w;
    }

    if (cw > 0 && pw > 0) {
      setContainerWidth(cw);
      setCharWidth(pw);
    }

    const mc = cw > 0 && pw > 0 ? Math.max(1, Math.floor(cw / pw)) : 40;

    startWidth.current = cw;
    resizeWarned.current = false;
    start(mc);
    inputRef.current?.focus({ preventScroll: true });
  };

  const elapsedMs = state.firstKeyAt > 0 ? Date.now() - state.firstKeyAt : 0;
  const elapsedMin = elapsedMs / 60000;
  const cpm = elapsedMin > 0 ? Math.round(state.hits / elapsedMin) : 0;
  const accuracy = state.keys === 0 ? 100 : (state.hits / state.keys) * 100;

  const stats = {
    cpm,
    acc: accuracy.toFixed(1),
    keys: state.keys,
    errors: state.misses,
    time: formatTime(elapsedMs),
  };

  const handleCopy = async () => {
    const payload = [
      `CPM: ${stats.cpm}`,
      `Acc: ${stats.acc}%`,
      `Keys: ${stats.keys}`,
      `Errors: ${stats.errors}`,
      `Time: ${stats.time}`,
      '',
      `Pool: ${pool}`,
      '',
      'InfiniteType By PabitraMS',
      'Generated By toolpabitrams',
      TOOLKIT_URL,
    ].join('\n');

    try {
      await navigator.clipboard.writeText(payload);
      showToast(
        'success',
        <FiCopy size={18} />,
        'Copied',
        'Stats copied to clipboard.'
      );
    } catch {
      showToast(
        'error',
        <MdWarningAmber size={18} />,
        'Copy failed',
        'Could not access clipboard.'
      );
    }
  };

  const handleInput = (e: React.FormEvent<HTMLInputElement>) => {
    if (!isRunning) return;
    const input = e.currentTarget;
    const value = input.value;
    if (value.length > 0) {
      for (let i = 0; i < value.length; i++) {
        typeChar(value[i]);
      }
      input.value = '';
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (!isRunning) return;

    const key = e.key;
    if (key === 'Escape') {
      stop();
      return;
    }
    if (key === 'Backspace') {
      e.preventDefault();
      backspace();
      return;
    }
    if (key === 'Enter') {
      e.preventDefault();
      enter(maxChars);
      return;
    }
  };

  const focusInput = () => {
    if (isRunning) inputRef.current?.focus({ preventScroll: true });
  };

  return (
    <div
      className="w-full py-6 px-4 sm:px-6 lg:px-8"
      onClick={focusInput}
    >
      <input
        ref={inputRef}
        type="text"
        inputMode="text"
        autoComplete="off"
        autoCorrect="off"
        autoCapitalize="off"
        spellCheck={false}
        aria-label="Typing input"
        style={{
          position: 'fixed',
          top: 0,
          left: 0,
          width: '1px',
          height: '1px',
          opacity: 0,
          border: 'none',
          outline: 'none',
          padding: 0,
          margin: 0,
          fontSize: '16px',
          zIndex: -1,
          pointerEvents: 'none',
        }}
        onInput={handleInput}
        onKeyDown={handleKeyDown}
        onFocus={() => setIsFocused(true)}
        onBlur={() => setIsFocused(false)}
      />

      <div className="max-w-4xl mx-auto space-y-4">
        <Stagger delay={100}>
          <Motion
            preset={zoomIn}
            as="div"
            delay={0}
            style={{ opacity: 0, transform: 'scale(0.5)' }}
          >
            <Controls
              pool={pool}
              isRunning={isRunning}
              onPoolChange={setPool}
              onStart={handleStart}
              onStop={stop}
              onCopy={handleCopy}
              stats={stats}
            />
          </Motion>

          <Motion
            preset={zoomIn}
            as="div"
            delay={100}
            style={{ opacity: 0, transform: 'scale(0.5)' }}
          >
            <Viewport
              state={state}
              isRunning={isRunning}
              isFocused={isFocused}
              containerRef={containerRef}
              probeRef={probeRef}
              onContainerWidth={setContainerWidth}
              onCharWidth={setCharWidth}
            />
          </Motion>

          <Motion
            preset={zoomIn}
            as="div"
            delay={200}
            style={{ opacity: 0, transform: 'scale(0.5)' }}
          >
            <div className="text-xs text-gray-400 dark:text-gray-500 text-center py-2">
              {isRunning
                ? 'Type. Backspace to fix. Enter at the end for a new line. Escape to stop.'
                : 'Configure above and press Start.'}
            </div>
          </Motion>
        </Stagger>
      </div>
    </div>
  );
};