export function formatSummaryText({
  currency,
  total,
  perPerson,
  people,
  transactions,
}: {
  currency: string;
  total: number;
  perPerson: number;
  people: string[];
  transactions: { from: string; to: string; amount: number }[];
}): string {
  const lines: string[] = [];
  
  // ─── HEADER ───
  lines.push('BILL SPLIT SUMMARY');
  lines.push('');
  
  // ─── TOTALS ───
  // EXACTLY 9 spaces between "Total:" and amount, "Per Person:" and amount
  lines.push(`Total:         ${currency} ${total.toFixed(2)}`);
  lines.push(`Per Person:    ${currency} ${perPerson.toFixed(2)}`);
  lines.push('');
  
  // ─── GROUP MEMBERS ───
  lines.push(`Group Members (${people.length})`);
  lines.push(people.join(', '));
  lines.push('');
  
  // ─── TRANSACTIONS ───
  lines.push(`Transactions (${transactions.length})`);
  if (transactions.length === 0) {
    lines.push('All settled. Everyone is even.');
  } else {
    // Find the longest "from" and "to" names for padding
    const maxFromLen = Math.max(...transactions.map(t => t.from.length));
    const maxToLen = Math.max(...transactions.map(t => t.to.length));
    
    for (const tx of transactions) {
      // Pad names to max length, then EXACTLY 9 spaces, arrow, EXACTLY 9 spaces, amount
      const fromPadded = tx.from.padEnd(maxFromLen);
      const toPadded = tx.to.padEnd(maxToLen);
      const amountStr = `${currency} ${tx.amount.toFixed(2)}`;
      
      // EXACTLY 9 spaces between name and arrow, EXACTLY 9 spaces between arrow and to name
      // EXACTLY 9 spaces between to name and amount
      lines.push(`${fromPadded}         →  ${toPadded}         ${amountStr}`);
    }
  }
  lines.push('');
  
  // ─── BRANDING ───
  const dateStr = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  });
  lines.push('Generated by ToolPabitraMS');
  lines.push('https://toolpabitrams.pages.dev/');
  lines.push(dateStr);

  return lines.join('\n');
}