import { useCallback } from 'react';

interface UseSaveImageProps {
  currency: string;
  total: number;
  perPerson: number;
  people: string[];
  transactions: { from: string; to: string; amount: number }[];
  onSuccess: (message: string) => void;
  onError: (message: string) => void;
}

export function useSaveImage({
  currency,
  total,
  perPerson,
  people,
  transactions,
  onSuccess,
  onError,
}: UseSaveImageProps) {
  const saveImage = useCallback(async () => {
    try {
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        onError('Canvas not supported');
        return;
      }

      const width = 800;
      const height = 400 + transactions.length * 40 + people.length * 30;
      canvas.width = width;
      canvas.height = Math.max(height, 400);

      // Background
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // Title
      ctx.fillStyle = '#1a1a2e';
      ctx.font = 'bold 28px system-ui, sans-serif';
      ctx.fillText('Bill Split Summary', 40, 60);

      // Divider
      ctx.strokeStyle = '#e5e7eb';
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(40, 80);
      ctx.lineTo(canvas.width - 40, 80);
      ctx.stroke();

      // Totals
      ctx.font = '18px system-ui, sans-serif';
      ctx.fillStyle = '#16a34a';
      ctx.fillText(`Total: ${currency} ${total.toFixed(2)}`, 40, 120);
      ctx.fillStyle = '#3b82f6';
      ctx.fillText(`Per Person: ${currency} ${perPerson.toFixed(2)}`, 300, 120);

      // People
      ctx.fillStyle = '#6b7280';
      ctx.font = '16px system-ui, sans-serif';
      ctx.fillText(`Group Members (${people.length})`, 40, 165);
      
      // Wrap people names
      let yPos = 195;
      const peopleStr = people.join(', ');
      const maxWidth = width - 80;
      let currentLine = '';
      for (const char of peopleStr) {
        const testLine = currentLine + char;
        if (ctx.measureText(testLine).width > maxWidth) {
          ctx.fillStyle = '#6b7280';
          ctx.font = '14px system-ui, sans-serif';
          ctx.fillText(currentLine, 40, yPos);
          yPos += 22;
          currentLine = char;
        } else {
          currentLine = testLine;
        }
      }
      if (currentLine) {
        ctx.fillStyle = '#6b7280';
        ctx.font = '14px system-ui, sans-serif';
        ctx.fillText(currentLine, 40, yPos);
        yPos += 30;
      }

      // Transactions header
      ctx.fillStyle = '#1a1a2e';
      ctx.font = 'bold 18px system-ui, sans-serif';
      ctx.fillText(`Transactions (${transactions.length})`, 40, yPos);
      yPos += 35;

      if (transactions.length === 0) {
        ctx.fillStyle = '#22c55e';
        ctx.font = '16px system-ui, sans-serif';
        ctx.fillText('All settled. Everyone is even.', 40, yPos);
        yPos += 40;
      } else {
        transactions.forEach((tx, i) => {
          const bg = i % 2 === 0 ? '#f9fafb' : '#ffffff';
          ctx.fillStyle = bg;
          ctx.fillRect(40, yPos - 8, width - 80, 36);
          
          ctx.fillStyle = '#1a1a2e';
          ctx.font = '14px system-ui, sans-serif';
          ctx.fillText(tx.from, 60, yPos + 10);
          
          ctx.fillStyle = '#9ca3af';
          ctx.fillText('→', 220, yPos + 10);
          
          ctx.fillStyle = '#1a1a2e';
          ctx.fillText(tx.to, 250, yPos + 10);
          
          ctx.fillStyle = '#2563eb';
          ctx.font = 'bold 14px system-ui, sans-serif';
          ctx.fillText(`${currency} ${tx.amount.toFixed(2)}`, 550, yPos + 10);
          
          yPos += 40;
        });
      }

      const footerY = Math.max(yPos + 30, 420);
      ctx.fillStyle = '#9ca3af';
      ctx.font = '12px system-ui, sans-serif';
      
      const dateStr = new Date().toLocaleString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        hour12: false,
      });
      ctx.fillText('Generated by ToolPabitraMS', 40, footerY);
      ctx.fillText('https://toolpabitrams.pages.dev/', 40, footerY + 18);
      ctx.fillText(dateStr, 40, footerY + 36);

      const link = document.createElement('a');
      link.download = `bill-split-${Date.now()}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
      onSuccess('Image saved');
    } catch (err) {
      console.error('Save image failed:', err);
      onError('Failed to save');
    }
  }, [currency, total, perPerson, people, transactions, onSuccess, onError]);

  return { saveImage };
}